In [ ]:
import tensorflow as tf
print("tensorflow version : ", tf.__version__)

tensorflow version :  2.14.0


In [ ]:
import numpy as np
tensor_1d= np.array([3.3,1,4,5,8])
print(tensor_1d)
print(tensor_1d[4])

[3.3 1.  4.  5.  8. ]
8.0


In [ ]:
tensor_2d= np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(tensor_2d)
print(tensor_2d[2][2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
9


In [ ]:
mat1= np.array([(2,2,2),(4,4,4),(8,8,8)],dtype='int32')
mat2= np.array([(1,1,1),(3,3,3),(5,5,5)],dtype='int32')
print(mat1)
print()
print(mat2)

[[2 2 2]
 [4 4 4]
 [8 8 8]]

[[1 1 1]
 [3 3 3]
 [5 5 5]]


In [ ]:
mat1= tf.constant(mat1)
mat2= tf.constant(mat2)
print(mat1)
print(mat2)

tf.Tensor(
[[2 2 2]
 [4 4 4]
 [8 8 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [3 3 3]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [ ]:
mat_product= tf.matmul(mat1,mat2)
mat_sum= tf.add(mat1,mat2)
print(mat_product)
print(mat_sum)

tf.Tensor(
[[18 18 18]
 [36 36 36]
 [72 72 72]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 3  3  3]
 [ 7  7  7]
 [13 13 13]], shape=(3, 3), dtype=int32)


In [ ]:
mat3= np.array([(2,5,8),(4,8,6),(7,3,2)],dtype='float64')
print(mat3)
mat3=tf.constant(mat3)
print(mat3)
mat_det=tf.linalg.det(mat3)
print(mat_det)

[[2. 5. 8.]
 [4. 8. 6.]
 [7. 3. 2.]]
tf.Tensor(
[[2. 5. 8.]
 [4. 8. 6.]
 [7. 3. 2.]], shape=(3, 3), dtype=float64)
tf.Tensor(-185.99999999999991, shape=(), dtype=float64)


In [ ]:
import tensorflow as tf

var = tf.Variable(1)
ph = tf.constant(1.0, dtype=tf.float32)
print(var)
print(ph)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
import tensorflow as tf

# Create two tensors
tensor1 = tf.constant(5)
tensor2 = tf.constant(2)

# Add the two tensors together
sum_tensor = tf.add(tensor1, tensor2)

# Execute the TensorFlow operation
output = sum_tensor

# Print the output
print(output)



tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf

# Create two tensors
tensor1 = tf.constant(10)
tensor2 = tf.constant(5)

# Add the two tensors together
sum_tensor = tf.add(tensor1, tensor2)

# Execute the TensorFlow operation
output = tf.keras.backend.eval(sum_tensor)

# Print the output
print(output)


15


In [ ]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#Graph creation
x = tf.Variable(3, name="x")
y = tf.Variable(5, name="y")
f = x*x + y*y + 2

sess = tf.compat.v1.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)
sess.close()

msg = tf.constant('MACHINE LEARNING')
sess = tf.Session()
print(sess.run(msg))

36
b'MACHINE LEARNING'
